INSERT INTO users (id, email, password, username)
VALUES (1, 'john.doe@mail.com', '$2a$10$QetWj8TyArRfVa16aqk4/Ov5WpB5MIfy654pfyXSGCcXoXkzf7iXi', 'john.doe'),
       (2, 'amanda.brown@mail.com', '$2a$10$8.WjMlS.D.Zv.TeSBRRPzO9Vpd1yQyie31TEVHV2d.Zv1fZCgR6jW', 'amanda.brown');

INSERT INTO categories (id, name, description)
VALUES (1, 'Gelato', ''),
       (2, 'Gelato for special needs', ''),
       (3, 'Donuts', ''),
       (4, 'Donuts for special needs', ''),
       (5, 'Merchandise', '');

INSERT INTO products (id, title, type, category_id, price, currency, quantity, short_description,
                             long_description, ingredients,
                             allergens, photo_url)
VALUES (1, 'Pistachio Ice Cream', 'ICE_CREAM', 1, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/1.png'),
       (2, 'Watermelon Ice Cream', 'ICE_CREAM', 1, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/2.png'),
       (3, 'Strawberry Ice Cream', 'ICE_CREAM', 1, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/3.png'),
       (4, 'Watermelon Ice Cream', 'ICE_CREAM', 1, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/4.png'),
       (5, 'Pistachio Ice Cream', 'ICE_CREAM', 2, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/1.png'),
       (6, 'Watermelon Ice Cream', 'ICE_CREAM', 2, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/2.png'),
       (7, 'Strawberry Ice Cream', 'ICE_CREAM', 2, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/3.png'),
       (8, 'Watermelon Ice Cream', 'ICE_CREAM', 2, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/4.png'),
       (9, 'Vanilla Strawberry Donuts', 'DONUTS', 3, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/9.png'),
       (10, 'Rose Donuts', 'DONUTS', 3, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/10.png'),
       (11, 'Marshmallow Donuts', 'DONUTS', 3, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/11.png'),
       (12, 'Paradise Donuts', 'DONUTS', 3, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/12.png'),
       (13, 'Cocoa Donuts', 'DONUTS', 3, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/13.png'),
       (14, 'Banana Combo Donuts', 'DONUTS', 3, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/14.png'),
       (15, 'Chocolate Mix Donuts', 'DONUTS', 3, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/15.png'),
       (16, 'Gem Mix Donuts', 'DONUTS', 3, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/16.png'),
       (17, 'Toffee Donuts', 'DONUTS', 3, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/17.png'),
       (18, 'Cake Dough Donuts', 'DONUTS', 3, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/18.png'),
       (19, 'Cruise Donuts', 'DONUTS', 3, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/19.png'),
       (20, 'Ferrero Donuts', 'DONUTS', 3, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/20.png'),
       (21, 'Chocolate Donuts', 'DONUTS', 3, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/21.png'),
       (22, 'Strawberry Donuts', 'DONUTS', 3, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/22.png'),
       (23, 'Simple Donuts', 'DONUTS', 3, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/23.png'),
       (24, 'Chocolate Sprinkled Donuts', 'DONUTS', 3, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/24.png'),
       (25, 'KINDER BUENO', 'DONUTS', 3, 2.00, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/15.png'),
       (26, 'Vanilla Strawberry Donuts', 'DONUTS', 4, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/9.png'),
       (27, 'Rose Donuts', 'DONUTS', 4, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/10.png'),
       (28, 'Marshmallow Donuts', 'DONUTS', 4, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/11.png'),
       (29, 'Paradise Donuts', 'DONUTS', 4, 2.50, '$', 50,
        'Treat yourself to ice cream infused with smooth Bourbon sprinkled',
        'Donut with white chocolate icing, dark chocolate curls, Kinder Bueno ™ wafers and delicate milk chocolate lines',
        'Cream, Milk, Cane Sugar, Cake Pieces, Cake Base, Sprinkles (Sugar, Coconut Oil, Buttermilk Powder, Natural Flavor, Spirulina Extract, Skim Milk, Eggs)',
        'Milk, egg, soy, wheat',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/12.png'),
       (30, 'Basic T Shirts', 'MERCHANDISE', 5, 10.50, '$', 50,
        'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam',
        '',
        '',
        '',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/30.png'),
       (31, 'Simple Mug', 'MERCHANDISE', 5, 5.50, '$', 50,
        'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam',
        '',
        '',
        '',
        'https://candy-shop.s3.eu-central-1.amazonaws.com/31.png');

